# Generated by Django 4.2.1 on 2023-08-02 08:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=3)),
                ('postcode', models.CharField(max_length=4)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('completed_tutorial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(choices=[('Cloudy', 'Cloudy'), ('Sunny', 'Sunny'), ('Windy', 'Windy'), ('Rainy', 'Rainy')], max_length=25)),
                ('wind', models.CharField(choices=[('No Wind', 'No Wind'), ('Calm', 'Calm'), ('Windy', 'Windy')], max_length=25)),
                ('temperature', models.CharField(choices=[('Cool', 'Cool'), ('Warm', 'Warm'), ('Hot', 'Hot')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_period', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=25)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed')], default='Upcoming', max_length=100)),
                ('result', models.CharField(choices=[('Successful', 'Successful'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.user')),
                ('weather_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.weatheroption')),
            ],
        ),
        migrations.CreateModel(
            name='ActualWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_period', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=25)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.location')),
            ],
        ),
        migrations.AddConstraint(
            model_name='actualweather',
            constraint=models.UniqueConstraint(fields=('date', 'time_period', 'location'), name='actualweather_unique_datetime_location'),
        ),
    ]
