# Generated by Django 4.2.1 on 2023-10-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather_api", "0003_alter_feedback_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_name",
            field=models.CharField(default="Weather Booking", max_length=100),
        ),
    ]
